// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/kelar1s/go-freight/internal/inventory/model"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// AddProductQuantity provides a mock function with given fields: ctx, id, quantity
func (_m *Service) AddProductQuantity(ctx context.Context, id int32, quantity int32) error {
	ret := _m.Called(ctx, id, quantity)

	if len(ret) == 0 {
		panic("no return value specified for AddProductQuantity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) error); ok {
		r0 = rf(ctx, id, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_AddProductQuantity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddProductQuantity'
type Service_AddProductQuantity_Call struct {
	*mock.Call
}

// AddProductQuantity is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
//   - quantity int32
func (_e *Service_Expecter) AddProductQuantity(ctx interface{}, id interface{}, quantity interface{}) *Service_AddProductQuantity_Call {
	return &Service_AddProductQuantity_Call{Call: _e.mock.On("AddProductQuantity", ctx, id, quantity)}
}

func (_c *Service_AddProductQuantity_Call) Run(run func(ctx context.Context, id int32, quantity int32)) *Service_AddProductQuantity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32))
	})
	return _c
}

func (_c *Service_AddProductQuantity_Call) Return(_a0 error) *Service_AddProductQuantity_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_AddProductQuantity_Call) RunAndReturn(run func(context.Context, int32, int32) error) *Service_AddProductQuantity_Call {
	_c.Call.Return(run)
	return _c
}

// CancelReservation provides a mock function with given fields: ctx, id, quantity
func (_m *Service) CancelReservation(ctx context.Context, id int32, quantity int32) error {
	ret := _m.Called(ctx, id, quantity)

	if len(ret) == 0 {
		panic("no return value specified for CancelReservation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) error); ok {
		r0 = rf(ctx, id, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_CancelReservation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelReservation'
type Service_CancelReservation_Call struct {
	*mock.Call
}

// CancelReservation is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
//   - quantity int32
func (_e *Service_Expecter) CancelReservation(ctx interface{}, id interface{}, quantity interface{}) *Service_CancelReservation_Call {
	return &Service_CancelReservation_Call{Call: _e.mock.On("CancelReservation", ctx, id, quantity)}
}

func (_c *Service_CancelReservation_Call) Run(run func(ctx context.Context, id int32, quantity int32)) *Service_CancelReservation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32))
	})
	return _c
}

func (_c *Service_CancelReservation_Call) Return(_a0 error) *Service_CancelReservation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_CancelReservation_Call) RunAndReturn(run func(context.Context, int32, int32) error) *Service_CancelReservation_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProduct provides a mock function with given fields: ctx, warehouseID, name, quantity
func (_m *Service) CreateProduct(ctx context.Context, warehouseID int32, name string, quantity int32) (model.Product, error) {
	ret := _m.Called(ctx, warehouseID, name, quantity)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 model.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, string, int32) (model.Product, error)); ok {
		return rf(ctx, warehouseID, name, quantity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, string, int32) model.Product); ok {
		r0 = rf(ctx, warehouseID, name, quantity)
	} else {
		r0 = ret.Get(0).(model.Product)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, string, int32) error); ok {
		r1 = rf(ctx, warehouseID, name, quantity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_CreateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProduct'
type Service_CreateProduct_Call struct {
	*mock.Call
}

// CreateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - warehouseID int32
//   - name string
//   - quantity int32
func (_e *Service_Expecter) CreateProduct(ctx interface{}, warehouseID interface{}, name interface{}, quantity interface{}) *Service_CreateProduct_Call {
	return &Service_CreateProduct_Call{Call: _e.mock.On("CreateProduct", ctx, warehouseID, name, quantity)}
}

func (_c *Service_CreateProduct_Call) Run(run func(ctx context.Context, warehouseID int32, name string, quantity int32)) *Service_CreateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(string), args[3].(int32))
	})
	return _c
}

func (_c *Service_CreateProduct_Call) Return(_a0 model.Product, _a1 error) *Service_CreateProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_CreateProduct_Call) RunAndReturn(run func(context.Context, int32, string, int32) (model.Product, error)) *Service_CreateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWarehouse provides a mock function with given fields: ctx, name, location
func (_m *Service) CreateWarehouse(ctx context.Context, name string, location string) (model.Warehouse, error) {
	ret := _m.Called(ctx, name, location)

	if len(ret) == 0 {
		panic("no return value specified for CreateWarehouse")
	}

	var r0 model.Warehouse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (model.Warehouse, error)); ok {
		return rf(ctx, name, location)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) model.Warehouse); ok {
		r0 = rf(ctx, name, location)
	} else {
		r0 = ret.Get(0).(model.Warehouse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, name, location)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_CreateWarehouse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWarehouse'
type Service_CreateWarehouse_Call struct {
	*mock.Call
}

// CreateWarehouse is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - location string
func (_e *Service_Expecter) CreateWarehouse(ctx interface{}, name interface{}, location interface{}) *Service_CreateWarehouse_Call {
	return &Service_CreateWarehouse_Call{Call: _e.mock.On("CreateWarehouse", ctx, name, location)}
}

func (_c *Service_CreateWarehouse_Call) Run(run func(ctx context.Context, name string, location string)) *Service_CreateWarehouse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Service_CreateWarehouse_Call) Return(_a0 model.Warehouse, _a1 error) *Service_CreateWarehouse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_CreateWarehouse_Call) RunAndReturn(run func(context.Context, string, string) (model.Warehouse, error)) *Service_CreateWarehouse_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProduct provides a mock function with given fields: ctx, id
func (_m *Service) DeleteProduct(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_DeleteProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProduct'
type Service_DeleteProduct_Call struct {
	*mock.Call
}

// DeleteProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *Service_Expecter) DeleteProduct(ctx interface{}, id interface{}) *Service_DeleteProduct_Call {
	return &Service_DeleteProduct_Call{Call: _e.mock.On("DeleteProduct", ctx, id)}
}

func (_c *Service_DeleteProduct_Call) Run(run func(ctx context.Context, id int32)) *Service_DeleteProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *Service_DeleteProduct_Call) Return(_a0 error) *Service_DeleteProduct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_DeleteProduct_Call) RunAndReturn(run func(context.Context, int32) error) *Service_DeleteProduct_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWarehouse provides a mock function with given fields: ctx, id
func (_m *Service) DeleteWarehouse(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWarehouse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_DeleteWarehouse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWarehouse'
type Service_DeleteWarehouse_Call struct {
	*mock.Call
}

// DeleteWarehouse is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *Service_Expecter) DeleteWarehouse(ctx interface{}, id interface{}) *Service_DeleteWarehouse_Call {
	return &Service_DeleteWarehouse_Call{Call: _e.mock.On("DeleteWarehouse", ctx, id)}
}

func (_c *Service_DeleteWarehouse_Call) Run(run func(ctx context.Context, id int32)) *Service_DeleteWarehouse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *Service_DeleteWarehouse_Call) Return(_a0 error) *Service_DeleteWarehouse_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_DeleteWarehouse_Call) RunAndReturn(run func(context.Context, int32) error) *Service_DeleteWarehouse_Call {
	_c.Call.Return(run)
	return _c
}

// GetProduct provides a mock function with given fields: ctx, id
func (_m *Service) GetProduct(ctx context.Context, id int32) (model.Product, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProduct")
	}

	var r0 model.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (model.Product, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) model.Product); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Product)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProduct'
type Service_GetProduct_Call struct {
	*mock.Call
}

// GetProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *Service_Expecter) GetProduct(ctx interface{}, id interface{}) *Service_GetProduct_Call {
	return &Service_GetProduct_Call{Call: _e.mock.On("GetProduct", ctx, id)}
}

func (_c *Service_GetProduct_Call) Run(run func(ctx context.Context, id int32)) *Service_GetProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *Service_GetProduct_Call) Return(_a0 model.Product, _a1 error) *Service_GetProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetProduct_Call) RunAndReturn(run func(context.Context, int32) (model.Product, error)) *Service_GetProduct_Call {
	_c.Call.Return(run)
	return _c
}

// GetWarehouse provides a mock function with given fields: ctx, id
func (_m *Service) GetWarehouse(ctx context.Context, id int32) (model.Warehouse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetWarehouse")
	}

	var r0 model.Warehouse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (model.Warehouse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) model.Warehouse); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Warehouse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetWarehouse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWarehouse'
type Service_GetWarehouse_Call struct {
	*mock.Call
}

// GetWarehouse is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *Service_Expecter) GetWarehouse(ctx interface{}, id interface{}) *Service_GetWarehouse_Call {
	return &Service_GetWarehouse_Call{Call: _e.mock.On("GetWarehouse", ctx, id)}
}

func (_c *Service_GetWarehouse_Call) Run(run func(ctx context.Context, id int32)) *Service_GetWarehouse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *Service_GetWarehouse_Call) Return(_a0 model.Warehouse, _a1 error) *Service_GetWarehouse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetWarehouse_Call) RunAndReturn(run func(context.Context, int32) (model.Warehouse, error)) *Service_GetWarehouse_Call {
	_c.Call.Return(run)
	return _c
}

// ListProductsByWarehouse provides a mock function with given fields: ctx, warehouseID
func (_m *Service) ListProductsByWarehouse(ctx context.Context, warehouseID int32) ([]model.Product, error) {
	ret := _m.Called(ctx, warehouseID)

	if len(ret) == 0 {
		panic("no return value specified for ListProductsByWarehouse")
	}

	var r0 []model.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]model.Product, error)); ok {
		return rf(ctx, warehouseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []model.Product); ok {
		r0 = rf(ctx, warehouseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, warehouseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_ListProductsByWarehouse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProductsByWarehouse'
type Service_ListProductsByWarehouse_Call struct {
	*mock.Call
}

// ListProductsByWarehouse is a helper method to define mock.On call
//   - ctx context.Context
//   - warehouseID int32
func (_e *Service_Expecter) ListProductsByWarehouse(ctx interface{}, warehouseID interface{}) *Service_ListProductsByWarehouse_Call {
	return &Service_ListProductsByWarehouse_Call{Call: _e.mock.On("ListProductsByWarehouse", ctx, warehouseID)}
}

func (_c *Service_ListProductsByWarehouse_Call) Run(run func(ctx context.Context, warehouseID int32)) *Service_ListProductsByWarehouse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *Service_ListProductsByWarehouse_Call) Return(_a0 []model.Product, _a1 error) *Service_ListProductsByWarehouse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_ListProductsByWarehouse_Call) RunAndReturn(run func(context.Context, int32) ([]model.Product, error)) *Service_ListProductsByWarehouse_Call {
	_c.Call.Return(run)
	return _c
}

// ListWarehouses provides a mock function with given fields: ctx
func (_m *Service) ListWarehouses(ctx context.Context) ([]model.Warehouse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListWarehouses")
	}

	var r0 []model.Warehouse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Warehouse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Warehouse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Warehouse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_ListWarehouses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWarehouses'
type Service_ListWarehouses_Call struct {
	*mock.Call
}

// ListWarehouses is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Service_Expecter) ListWarehouses(ctx interface{}) *Service_ListWarehouses_Call {
	return &Service_ListWarehouses_Call{Call: _e.mock.On("ListWarehouses", ctx)}
}

func (_c *Service_ListWarehouses_Call) Run(run func(ctx context.Context)) *Service_ListWarehouses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Service_ListWarehouses_Call) Return(_a0 []model.Warehouse, _a1 error) *Service_ListWarehouses_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_ListWarehouses_Call) RunAndReturn(run func(context.Context) ([]model.Warehouse, error)) *Service_ListWarehouses_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseProduct provides a mock function with given fields: ctx, id, quantity
func (_m *Service) ReleaseProduct(ctx context.Context, id int32, quantity int32) error {
	ret := _m.Called(ctx, id, quantity)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) error); ok {
		r0 = rf(ctx, id, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_ReleaseProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseProduct'
type Service_ReleaseProduct_Call struct {
	*mock.Call
}

// ReleaseProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
//   - quantity int32
func (_e *Service_Expecter) ReleaseProduct(ctx interface{}, id interface{}, quantity interface{}) *Service_ReleaseProduct_Call {
	return &Service_ReleaseProduct_Call{Call: _e.mock.On("ReleaseProduct", ctx, id, quantity)}
}

func (_c *Service_ReleaseProduct_Call) Run(run func(ctx context.Context, id int32, quantity int32)) *Service_ReleaseProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32))
	})
	return _c
}

func (_c *Service_ReleaseProduct_Call) Return(_a0 error) *Service_ReleaseProduct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_ReleaseProduct_Call) RunAndReturn(run func(context.Context, int32, int32) error) *Service_ReleaseProduct_Call {
	_c.Call.Return(run)
	return _c
}

// ReserveProduct provides a mock function with given fields: ctx, id, quantity
func (_m *Service) ReserveProduct(ctx context.Context, id int32, quantity int32) error {
	ret := _m.Called(ctx, id, quantity)

	if len(ret) == 0 {
		panic("no return value specified for ReserveProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) error); ok {
		r0 = rf(ctx, id, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_ReserveProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReserveProduct'
type Service_ReserveProduct_Call struct {
	*mock.Call
}

// ReserveProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
//   - quantity int32
func (_e *Service_Expecter) ReserveProduct(ctx interface{}, id interface{}, quantity interface{}) *Service_ReserveProduct_Call {
	return &Service_ReserveProduct_Call{Call: _e.mock.On("ReserveProduct", ctx, id, quantity)}
}

func (_c *Service_ReserveProduct_Call) Run(run func(ctx context.Context, id int32, quantity int32)) *Service_ReserveProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32))
	})
	return _c
}

func (_c *Service_ReserveProduct_Call) Return(_a0 error) *Service_ReserveProduct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_ReserveProduct_Call) RunAndReturn(run func(context.Context, int32, int32) error) *Service_ReserveProduct_Call {
	_c.Call.Return(run)
	return _c
}

// SetProductQuantity provides a mock function with given fields: ctx, id, quantity
func (_m *Service) SetProductQuantity(ctx context.Context, id int32, quantity int32) error {
	ret := _m.Called(ctx, id, quantity)

	if len(ret) == 0 {
		panic("no return value specified for SetProductQuantity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) error); ok {
		r0 = rf(ctx, id, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_SetProductQuantity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetProductQuantity'
type Service_SetProductQuantity_Call struct {
	*mock.Call
}

// SetProductQuantity is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
//   - quantity int32
func (_e *Service_Expecter) SetProductQuantity(ctx interface{}, id interface{}, quantity interface{}) *Service_SetProductQuantity_Call {
	return &Service_SetProductQuantity_Call{Call: _e.mock.On("SetProductQuantity", ctx, id, quantity)}
}

func (_c *Service_SetProductQuantity_Call) Run(run func(ctx context.Context, id int32, quantity int32)) *Service_SetProductQuantity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32))
	})
	return _c
}

func (_c *Service_SetProductQuantity_Call) Return(_a0 error) *Service_SetProductQuantity_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_SetProductQuantity_Call) RunAndReturn(run func(context.Context, int32, int32) error) *Service_SetProductQuantity_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWarehouse provides a mock function with given fields: ctx, id, name, location
func (_m *Service) UpdateWarehouse(ctx context.Context, id int32, name string, location string) error {
	ret := _m.Called(ctx, id, name, location)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWarehouse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, string, string) error); ok {
		r0 = rf(ctx, id, name, location)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_UpdateWarehouse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWarehouse'
type Service_UpdateWarehouse_Call struct {
	*mock.Call
}

// UpdateWarehouse is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
//   - name string
//   - location string
func (_e *Service_Expecter) UpdateWarehouse(ctx interface{}, id interface{}, name interface{}, location interface{}) *Service_UpdateWarehouse_Call {
	return &Service_UpdateWarehouse_Call{Call: _e.mock.On("UpdateWarehouse", ctx, id, name, location)}
}

func (_c *Service_UpdateWarehouse_Call) Run(run func(ctx context.Context, id int32, name string, location string)) *Service_UpdateWarehouse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *Service_UpdateWarehouse_Call) Return(_a0 error) *Service_UpdateWarehouse_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_UpdateWarehouse_Call) RunAndReturn(run func(context.Context, int32, string, string) error) *Service_UpdateWarehouse_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
