// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pg

import (
	"time"
)

type Product struct {
	ID          int64
	WarehouseID int64
	Name        string
	CreatedAt   time.Time
}

type ProductStock struct {
	ProductID int64
	Quantity  int64
	Reserved  int64
}

type Warehouse struct {
	ID        int64
	Name      string
	Location  string
	CreatedAt time.Time
}
