// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pg

import (
	"time"
)

type Product struct {
	ID          int64
	WarehouseID int64
	Name        string
	Quantity    int64
	CreatedAt   time.Time
	Reserved    int64
}

type Warehouse struct {
	ID        int64
	Name      string
	Location  string
	CreatedAt time.Time
}
