// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: products.sql

package pg

import (
	"context"
)

const addProductQuantity = `-- name: AddProductQuantity :one
UPDATE products SET quantity = quantity + $2 WHERE id = $1 RETURNING id
`

type AddProductQuantityParams struct {
	ID       int32
	Quantity int32
}

func (q *Queries) AddProductQuantity(ctx context.Context, arg AddProductQuantityParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, addProductQuantity, arg.ID, arg.Quantity)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const cancelReservation = `-- name: CancelReservation :one
UPDATE products SET reserved = reserved - $2 WHERE id = $1 AND reserved >= $2 RETURNING id
`

type CancelReservationParams struct {
	ID       int32
	Reserved int32
}

func (q *Queries) CancelReservation(ctx context.Context, arg CancelReservationParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, cancelReservation, arg.ID, arg.Reserved)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products(warehouse_id, name, quantity, reserved) VALUES($1, $2, $3, 0) RETURNING id, warehouse_id, name, quantity, created_at, reserved
`

type CreateProductParams struct {
	WarehouseID int32
	Name        string
	Quantity    int32
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct, arg.WarehouseID, arg.Name, arg.Quantity)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.WarehouseID,
		&i.Name,
		&i.Quantity,
		&i.CreatedAt,
		&i.Reserved,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :one
DELETE FROM products WHERE id = $1 RETURNING id
`

func (q *Queries) DeleteProduct(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, deleteProduct, id)
	var id_2 int32
	err := row.Scan(&id_2)
	return id_2, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, warehouse_id, name, quantity, created_at, reserved FROM products WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, id int32) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.WarehouseID,
		&i.Name,
		&i.Quantity,
		&i.CreatedAt,
		&i.Reserved,
	)
	return i, err
}

const listProductsByWarehouse = `-- name: ListProductsByWarehouse :many
SELECT id, warehouse_id, name, quantity, created_at, reserved FROM products WHERE warehouse_id = $1 ORDER BY id
`

func (q *Queries) ListProductsByWarehouse(ctx context.Context, warehouseID int32) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByWarehouse, warehouseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.WarehouseID,
			&i.Name,
			&i.Quantity,
			&i.CreatedAt,
			&i.Reserved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseProduct = `-- name: ReleaseProduct :one
UPDATE products SET quantity = quantity - $2, reserved = reserved - $2 WHERE id = $1 AND reserved >= $2 AND quantity >= $2 RETURNING id
`

type ReleaseProductParams struct {
	ID       int32
	Quantity int32
}

func (q *Queries) ReleaseProduct(ctx context.Context, arg ReleaseProductParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, releaseProduct, arg.ID, arg.Quantity)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const reserveProduct = `-- name: ReserveProduct :one
UPDATE products SET reserved = reserved + $2 WHERE id = $1 AND (quantity - reserved) >= $2 RETURNING id
`

type ReserveProductParams struct {
	ID       int32
	Reserved int32
}

func (q *Queries) ReserveProduct(ctx context.Context, arg ReserveProductParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, reserveProduct, arg.ID, arg.Reserved)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const setProductQuantity = `-- name: SetProductQuantity :one
UPDATE products SET quantity = $2 WHERE id = $1 RETURNING id
`

type SetProductQuantityParams struct {
	ID       int32
	Quantity int32
}

func (q *Queries) SetProductQuantity(ctx context.Context, arg SetProductQuantityParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, setProductQuantity, arg.ID, arg.Quantity)
	var id int32
	err := row.Scan(&id)
	return id, err
}
