// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package pg

import (
	"context"
)

const addProductQuantity = `-- name: AddProductQuantity :exec
UPDATE products SET quantity = quantity + $2 WHERE id = $1
`

type AddProductQuantityParams struct {
	ID       int32
	Quantity int32
}

func (q *Queries) AddProductQuantity(ctx context.Context, arg AddProductQuantityParams) error {
	_, err := q.db.ExecContext(ctx, addProductQuantity, arg.ID, arg.Quantity)
	return err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products(warehouse_id, name, quantity) VALUES($1, $2, $3) RETURNING id, warehouse_id, name, quantity, created_at
`

type CreateProductParams struct {
	WarehouseID int32
	Name        string
	Quantity    int32
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct, arg.WarehouseID, arg.Name, arg.Quantity)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.WarehouseID,
		&i.Name,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, warehouse_id, name, quantity, created_at FROM products WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, id int32) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.WarehouseID,
		&i.Name,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const listProductsByWarehouse = `-- name: ListProductsByWarehouse :many
SELECT id, warehouse_id, name, quantity, created_at FROM products WHERE warehouse_id = $1 ORDER BY id
`

func (q *Queries) ListProductsByWarehouse(ctx context.Context, warehouseID int32) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByWarehouse, warehouseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.WarehouseID,
			&i.Name,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProductQuantity = `-- name: SetProductQuantity :exec
UPDATE products SET quantity = $2 WHERE id = $1
`

type SetProductQuantityParams struct {
	ID       int32
	Quantity int32
}

func (q *Queries) SetProductQuantity(ctx context.Context, arg SetProductQuantityParams) error {
	_, err := q.db.ExecContext(ctx, setProductQuantity, arg.ID, arg.Quantity)
	return err
}
