version: '3'

dotenv: ['.env']

vars:
  CONFIG_PATH: './config/local.yaml'
  APP_ENTRY: 'cmd/inventory/main.go'
  DOCKER_CONFIG: 'docker-compose.yml'
  DB_DSN: "user=postgres password={{.DB_PASSWORD}} dbname=gofreight host=localhost port=5433 sslmode=disable"
  MIGRATIONS_DIR: "db/migrations/inventory"

tasks:
  default:
    cmds:
      - task --list
    silent: true

  up:
    desc: "Собрать и поднять всё в Docker (с пересборкой)"
    cmds:
      - docker compose up -d --build

  infra:
    desc: "Поднять базовую инфраструктуру (БД и Redis)"
    cmds:
      - docker compose up -d db redis

  obs:
    desc: "Поднять стек наблюдаемости (Tempo, Loki, Prometheus, Grafana)"
    cmds:
      - docker compose up -d tempo loki prometheus grafana

  infra-all:
    desc: "Поднять базу, кэш и всю наблюдаемость для локальной разработки"
    cmds:
      - docker compose up -d db redis tempo loki prometheus grafana
      
  migrate-create:
    desc: "Создать новый файл миграции: task migrate-create -- name_of_migration"
    cmds:
      - goose -dir {{.MIGRATIONS_DIR}} create {{.CLI_ARGS}} sql
      
  migrate-up:
    desc: "Накатить миграции склада"
    cmds:
      - goose -dir {{.MIGRATIONS_DIR}} postgres "{{.DB_DSN}}" up

  migrate-status:
    desc: "Проверить статус миграций"
    cmds:
      - goose -dir {{.MIGRATIONS_DIR}} postgres "{{.DB_DSN}}" status

  migrate-reset:
    desc: "Сбросить все миграции"
    cmds:
      - goose -dir {{.MIGRATIONS_DIR}} postgres "{{.DB_DSN}}" reset

  down:
    desc: "Остановить и удалить контейнеры и сети"
    cmds:
      - docker compose down

  logs:
    desc: "Смотреть логи приложения в реальном времени"
    cmds:
      - docker logs -f gofreight_inventory

  run:
    desc: "Запустить сервер локально (нужен поднятый 'task db')"
    cmds:
      - CONFIG_PATH={{.CONFIG_PATH}} go run {{.APP_ENTRY}}

  test:
    desc: "Запустить все тесты"
    cmds:
      - go test -v -race -timeout 30s ./...

  cover:
    desc: "Покрытие кода в браузере"
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out
      - rm coverage.out

  swagger:
    desc: "Сгенерировать документацию Swagger (OpenAPI)"
    cmds:
      - swag init -g {{.APP_ENTRY}} -o docs --parseDependency --parseInternal

  gen:
    desc: "Генерация моков и sqlc"
    cmds:
      - go generate ./...
      - sqlc generate
    silent: false

  tidy:
    desc: "Очистить и обновить зависимости go.mod"
    cmds:
      - go mod tidy
      - go mod verify

  lint:
    desc: "Запустить линтер"
    cmds:
      - golangci-lint run