// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pg

import (
	"time"
)

type Product struct {
	ID          int32
	WarehouseID int32
	Name        string
	Quantity    int32
	CreatedAt   time.Time
}

type Warehouse struct {
	ID        int32
	Name      string
	Location  string
	CreatedAt time.Time
}
