// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: warehouses.sql

package pg

import (
	"context"
)

const createWarehouse = `-- name: CreateWarehouse :one
INSERT INTO warehouses(name, location) VALUES($1, $2) RETURNING id, name, location, created_at
`

type CreateWarehouseParams struct {
	Name     string
	Location string
}

func (q *Queries) CreateWarehouse(ctx context.Context, arg CreateWarehouseParams) (Warehouse, error) {
	row := q.db.QueryRowContext(ctx, createWarehouse, arg.Name, arg.Location)
	var i Warehouse
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWarehouse = `-- name: DeleteWarehouse :exec
DELETE FROM warehouses WHERE id = $1
`

func (q *Queries) DeleteWarehouse(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteWarehouse, id)
	return err
}

const getWarehouse = `-- name: GetWarehouse :one
SELECT id, name, location, created_at FROM warehouses WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWarehouse(ctx context.Context, id int32) (Warehouse, error) {
	row := q.db.QueryRowContext(ctx, getWarehouse, id)
	var i Warehouse
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}

const listWarehouses = `-- name: ListWarehouses :many
SELECT id, name, location, created_at FROM warehouses
`

func (q *Queries) ListWarehouses(ctx context.Context) ([]Warehouse, error) {
	rows, err := q.db.QueryContext(ctx, listWarehouses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Warehouse
	for rows.Next() {
		var i Warehouse
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Location,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWarehouse = `-- name: UpdateWarehouse :exec
UPDATE warehouses SET name = $2, location = $3 WHERE id = $1
`

type UpdateWarehouseParams struct {
	ID       int32
	Name     string
	Location string
}

func (q *Queries) UpdateWarehouse(ctx context.Context, arg UpdateWarehouseParams) error {
	_, err := q.db.ExecContext(ctx, updateWarehouse, arg.ID, arg.Name, arg.Location)
	return err
}
