env: "local"

http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s

database:
  host: "localhost"
  port: 5433
  user: "postgres"
  password: "${DB_PASSWORD}"
  db_name: "gofreight"
  ssl_mode: "disable"

redis:
  host: "localhost"
  port: 6379
  password: "${REDIS_PASSWORD}"
  db: 0
  ttl: "5m"
  dial_timeout: "1s"
  read_timeout: "200ms"
  write_timeout: "200ms"

telemetry:
  service_name: "inventory"
  tempo_endpoint: "localhost:4317" 