// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/kelar1s/go-freight/internal/inventory/model"
	mock "github.com/stretchr/testify/mock"
)

// ProductRepo is an autogenerated mock type for the ProductRepo type
type ProductRepo struct {
	mock.Mock
}

type ProductRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *ProductRepo) EXPECT() *ProductRepo_Expecter {
	return &ProductRepo_Expecter{mock: &_m.Mock}
}

// AdjustQuantity provides a mock function with given fields: ctx, id, quantity
func (_m *ProductRepo) AdjustQuantity(ctx context.Context, id int64, quantity int64) error {
	ret := _m.Called(ctx, id, quantity)

	if len(ret) == 0 {
		panic("no return value specified for AdjustQuantity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, id, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProductRepo_AdjustQuantity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdjustQuantity'
type ProductRepo_AdjustQuantity_Call struct {
	*mock.Call
}

// AdjustQuantity is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - quantity int64
func (_e *ProductRepo_Expecter) AdjustQuantity(ctx interface{}, id interface{}, quantity interface{}) *ProductRepo_AdjustQuantity_Call {
	return &ProductRepo_AdjustQuantity_Call{Call: _e.mock.On("AdjustQuantity", ctx, id, quantity)}
}

func (_c *ProductRepo_AdjustQuantity_Call) Run(run func(ctx context.Context, id int64, quantity int64)) *ProductRepo_AdjustQuantity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *ProductRepo_AdjustQuantity_Call) Return(_a0 error) *ProductRepo_AdjustQuantity_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProductRepo_AdjustQuantity_Call) RunAndReturn(run func(context.Context, int64, int64) error) *ProductRepo_AdjustQuantity_Call {
	_c.Call.Return(run)
	return _c
}

// CancelReservation provides a mock function with given fields: ctx, id, quantity
func (_m *ProductRepo) CancelReservation(ctx context.Context, id int64, quantity int64) error {
	ret := _m.Called(ctx, id, quantity)

	if len(ret) == 0 {
		panic("no return value specified for CancelReservation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, id, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProductRepo_CancelReservation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelReservation'
type ProductRepo_CancelReservation_Call struct {
	*mock.Call
}

// CancelReservation is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - quantity int64
func (_e *ProductRepo_Expecter) CancelReservation(ctx interface{}, id interface{}, quantity interface{}) *ProductRepo_CancelReservation_Call {
	return &ProductRepo_CancelReservation_Call{Call: _e.mock.On("CancelReservation", ctx, id, quantity)}
}

func (_c *ProductRepo_CancelReservation_Call) Run(run func(ctx context.Context, id int64, quantity int64)) *ProductRepo_CancelReservation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *ProductRepo_CancelReservation_Call) Return(_a0 error) *ProductRepo_CancelReservation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProductRepo_CancelReservation_Call) RunAndReturn(run func(context.Context, int64, int64) error) *ProductRepo_CancelReservation_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, product
func (_m *ProductRepo) Create(ctx context.Context, product *model.Product) error {
	ret := _m.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Product) error); ok {
		r0 = rf(ctx, product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProductRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ProductRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - product *model.Product
func (_e *ProductRepo_Expecter) Create(ctx interface{}, product interface{}) *ProductRepo_Create_Call {
	return &ProductRepo_Create_Call{Call: _e.mock.On("Create", ctx, product)}
}

func (_c *ProductRepo_Create_Call) Run(run func(ctx context.Context, product *model.Product)) *ProductRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Product))
	})
	return _c
}

func (_c *ProductRepo_Create_Call) Return(_a0 error) *ProductRepo_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProductRepo_Create_Call) RunAndReturn(run func(context.Context, *model.Product) error) *ProductRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ProductRepo) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProductRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ProductRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *ProductRepo_Expecter) Delete(ctx interface{}, id interface{}) *ProductRepo_Delete_Call {
	return &ProductRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *ProductRepo_Delete_Call) Run(run func(ctx context.Context, id int64)) *ProductRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *ProductRepo_Delete_Call) Return(_a0 error) *ProductRepo_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProductRepo_Delete_Call) RunAndReturn(run func(context.Context, int64) error) *ProductRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetMeta provides a mock function with given fields: ctx, id
func (_m *ProductRepo) GetMeta(ctx context.Context, id int64) (*model.ProductMeta, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMeta")
	}

	var r0 *model.ProductMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.ProductMeta, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.ProductMeta); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ProductMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProductRepo_GetMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMeta'
type ProductRepo_GetMeta_Call struct {
	*mock.Call
}

// GetMeta is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *ProductRepo_Expecter) GetMeta(ctx interface{}, id interface{}) *ProductRepo_GetMeta_Call {
	return &ProductRepo_GetMeta_Call{Call: _e.mock.On("GetMeta", ctx, id)}
}

func (_c *ProductRepo_GetMeta_Call) Run(run func(ctx context.Context, id int64)) *ProductRepo_GetMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *ProductRepo_GetMeta_Call) Return(_a0 *model.ProductMeta, _a1 error) *ProductRepo_GetMeta_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProductRepo_GetMeta_Call) RunAndReturn(run func(context.Context, int64) (*model.ProductMeta, error)) *ProductRepo_GetMeta_Call {
	_c.Call.Return(run)
	return _c
}

// GetStock provides a mock function with given fields: ctx, id
func (_m *ProductRepo) GetStock(ctx context.Context, id int64) (*model.ProductStock, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetStock")
	}

	var r0 *model.ProductStock
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.ProductStock, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.ProductStock); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ProductStock)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProductRepo_GetStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStock'
type ProductRepo_GetStock_Call struct {
	*mock.Call
}

// GetStock is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *ProductRepo_Expecter) GetStock(ctx interface{}, id interface{}) *ProductRepo_GetStock_Call {
	return &ProductRepo_GetStock_Call{Call: _e.mock.On("GetStock", ctx, id)}
}

func (_c *ProductRepo_GetStock_Call) Run(run func(ctx context.Context, id int64)) *ProductRepo_GetStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *ProductRepo_GetStock_Call) Return(_a0 *model.ProductStock, _a1 error) *ProductRepo_GetStock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProductRepo_GetStock_Call) RunAndReturn(run func(context.Context, int64) (*model.ProductStock, error)) *ProductRepo_GetStock_Call {
	_c.Call.Return(run)
	return _c
}

// ListByWarehouse provides a mock function with given fields: ctx, warehouseID
func (_m *ProductRepo) ListByWarehouse(ctx context.Context, warehouseID int64) ([]model.Product, error) {
	ret := _m.Called(ctx, warehouseID)

	if len(ret) == 0 {
		panic("no return value specified for ListByWarehouse")
	}

	var r0 []model.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]model.Product, error)); ok {
		return rf(ctx, warehouseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []model.Product); ok {
		r0 = rf(ctx, warehouseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, warehouseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProductRepo_ListByWarehouse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByWarehouse'
type ProductRepo_ListByWarehouse_Call struct {
	*mock.Call
}

// ListByWarehouse is a helper method to define mock.On call
//   - ctx context.Context
//   - warehouseID int64
func (_e *ProductRepo_Expecter) ListByWarehouse(ctx interface{}, warehouseID interface{}) *ProductRepo_ListByWarehouse_Call {
	return &ProductRepo_ListByWarehouse_Call{Call: _e.mock.On("ListByWarehouse", ctx, warehouseID)}
}

func (_c *ProductRepo_ListByWarehouse_Call) Run(run func(ctx context.Context, warehouseID int64)) *ProductRepo_ListByWarehouse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *ProductRepo_ListByWarehouse_Call) Return(_a0 []model.Product, _a1 error) *ProductRepo_ListByWarehouse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProductRepo_ListByWarehouse_Call) RunAndReturn(run func(context.Context, int64) ([]model.Product, error)) *ProductRepo_ListByWarehouse_Call {
	_c.Call.Return(run)
	return _c
}

// Release provides a mock function with given fields: ctx, id, quantity
func (_m *ProductRepo) Release(ctx context.Context, id int64, quantity int64) error {
	ret := _m.Called(ctx, id, quantity)

	if len(ret) == 0 {
		panic("no return value specified for Release")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, id, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProductRepo_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type ProductRepo_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - quantity int64
func (_e *ProductRepo_Expecter) Release(ctx interface{}, id interface{}, quantity interface{}) *ProductRepo_Release_Call {
	return &ProductRepo_Release_Call{Call: _e.mock.On("Release", ctx, id, quantity)}
}

func (_c *ProductRepo_Release_Call) Run(run func(ctx context.Context, id int64, quantity int64)) *ProductRepo_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *ProductRepo_Release_Call) Return(_a0 error) *ProductRepo_Release_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProductRepo_Release_Call) RunAndReturn(run func(context.Context, int64, int64) error) *ProductRepo_Release_Call {
	_c.Call.Return(run)
	return _c
}

// Reserve provides a mock function with given fields: ctx, id, quantity
func (_m *ProductRepo) Reserve(ctx context.Context, id int64, quantity int64) error {
	ret := _m.Called(ctx, id, quantity)

	if len(ret) == 0 {
		panic("no return value specified for Reserve")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, id, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProductRepo_Reserve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reserve'
type ProductRepo_Reserve_Call struct {
	*mock.Call
}

// Reserve is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - quantity int64
func (_e *ProductRepo_Expecter) Reserve(ctx interface{}, id interface{}, quantity interface{}) *ProductRepo_Reserve_Call {
	return &ProductRepo_Reserve_Call{Call: _e.mock.On("Reserve", ctx, id, quantity)}
}

func (_c *ProductRepo_Reserve_Call) Run(run func(ctx context.Context, id int64, quantity int64)) *ProductRepo_Reserve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *ProductRepo_Reserve_Call) Return(_a0 error) *ProductRepo_Reserve_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProductRepo_Reserve_Call) RunAndReturn(run func(context.Context, int64, int64) error) *ProductRepo_Reserve_Call {
	_c.Call.Return(run)
	return _c
}

// NewProductRepo creates a new instance of ProductRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductRepo {
	mock := &ProductRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
