// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/kelar1s/go-freight/internal/inventory/model"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// AddProductQuantity provides a mock function with given fields: ctx, id, quantity
func (_m *Repository) AddProductQuantity(ctx context.Context, id int32, quantity int32) error {
	ret := _m.Called(ctx, id, quantity)

	if len(ret) == 0 {
		panic("no return value specified for AddProductQuantity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) error); ok {
		r0 = rf(ctx, id, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_AddProductQuantity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddProductQuantity'
type Repository_AddProductQuantity_Call struct {
	*mock.Call
}

// AddProductQuantity is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
//   - quantity int32
func (_e *Repository_Expecter) AddProductQuantity(ctx interface{}, id interface{}, quantity interface{}) *Repository_AddProductQuantity_Call {
	return &Repository_AddProductQuantity_Call{Call: _e.mock.On("AddProductQuantity", ctx, id, quantity)}
}

func (_c *Repository_AddProductQuantity_Call) Run(run func(ctx context.Context, id int32, quantity int32)) *Repository_AddProductQuantity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32))
	})
	return _c
}

func (_c *Repository_AddProductQuantity_Call) Return(_a0 error) *Repository_AddProductQuantity_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_AddProductQuantity_Call) RunAndReturn(run func(context.Context, int32, int32) error) *Repository_AddProductQuantity_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProduct provides a mock function with given fields: ctx, warehouseID, name, quantity
func (_m *Repository) CreateProduct(ctx context.Context, warehouseID int32, name string, quantity int32) (model.Product, error) {
	ret := _m.Called(ctx, warehouseID, name, quantity)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 model.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, string, int32) (model.Product, error)); ok {
		return rf(ctx, warehouseID, name, quantity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, string, int32) model.Product); ok {
		r0 = rf(ctx, warehouseID, name, quantity)
	} else {
		r0 = ret.Get(0).(model.Product)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, string, int32) error); ok {
		r1 = rf(ctx, warehouseID, name, quantity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_CreateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProduct'
type Repository_CreateProduct_Call struct {
	*mock.Call
}

// CreateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - warehouseID int32
//   - name string
//   - quantity int32
func (_e *Repository_Expecter) CreateProduct(ctx interface{}, warehouseID interface{}, name interface{}, quantity interface{}) *Repository_CreateProduct_Call {
	return &Repository_CreateProduct_Call{Call: _e.mock.On("CreateProduct", ctx, warehouseID, name, quantity)}
}

func (_c *Repository_CreateProduct_Call) Run(run func(ctx context.Context, warehouseID int32, name string, quantity int32)) *Repository_CreateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(string), args[3].(int32))
	})
	return _c
}

func (_c *Repository_CreateProduct_Call) Return(_a0 model.Product, _a1 error) *Repository_CreateProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_CreateProduct_Call) RunAndReturn(run func(context.Context, int32, string, int32) (model.Product, error)) *Repository_CreateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWarehouse provides a mock function with given fields: ctx, name, location
func (_m *Repository) CreateWarehouse(ctx context.Context, name string, location string) (model.Warehouse, error) {
	ret := _m.Called(ctx, name, location)

	if len(ret) == 0 {
		panic("no return value specified for CreateWarehouse")
	}

	var r0 model.Warehouse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (model.Warehouse, error)); ok {
		return rf(ctx, name, location)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) model.Warehouse); ok {
		r0 = rf(ctx, name, location)
	} else {
		r0 = ret.Get(0).(model.Warehouse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, name, location)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_CreateWarehouse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWarehouse'
type Repository_CreateWarehouse_Call struct {
	*mock.Call
}

// CreateWarehouse is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - location string
func (_e *Repository_Expecter) CreateWarehouse(ctx interface{}, name interface{}, location interface{}) *Repository_CreateWarehouse_Call {
	return &Repository_CreateWarehouse_Call{Call: _e.mock.On("CreateWarehouse", ctx, name, location)}
}

func (_c *Repository_CreateWarehouse_Call) Run(run func(ctx context.Context, name string, location string)) *Repository_CreateWarehouse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Repository_CreateWarehouse_Call) Return(_a0 model.Warehouse, _a1 error) *Repository_CreateWarehouse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_CreateWarehouse_Call) RunAndReturn(run func(context.Context, string, string) (model.Warehouse, error)) *Repository_CreateWarehouse_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProduct provides a mock function with given fields: ctx, id
func (_m *Repository) DeleteProduct(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_DeleteProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProduct'
type Repository_DeleteProduct_Call struct {
	*mock.Call
}

// DeleteProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *Repository_Expecter) DeleteProduct(ctx interface{}, id interface{}) *Repository_DeleteProduct_Call {
	return &Repository_DeleteProduct_Call{Call: _e.mock.On("DeleteProduct", ctx, id)}
}

func (_c *Repository_DeleteProduct_Call) Run(run func(ctx context.Context, id int32)) *Repository_DeleteProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *Repository_DeleteProduct_Call) Return(_a0 error) *Repository_DeleteProduct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_DeleteProduct_Call) RunAndReturn(run func(context.Context, int32) error) *Repository_DeleteProduct_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWarehouse provides a mock function with given fields: ctx, id
func (_m *Repository) DeleteWarehouse(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWarehouse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_DeleteWarehouse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWarehouse'
type Repository_DeleteWarehouse_Call struct {
	*mock.Call
}

// DeleteWarehouse is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *Repository_Expecter) DeleteWarehouse(ctx interface{}, id interface{}) *Repository_DeleteWarehouse_Call {
	return &Repository_DeleteWarehouse_Call{Call: _e.mock.On("DeleteWarehouse", ctx, id)}
}

func (_c *Repository_DeleteWarehouse_Call) Run(run func(ctx context.Context, id int32)) *Repository_DeleteWarehouse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *Repository_DeleteWarehouse_Call) Return(_a0 error) *Repository_DeleteWarehouse_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_DeleteWarehouse_Call) RunAndReturn(run func(context.Context, int32) error) *Repository_DeleteWarehouse_Call {
	_c.Call.Return(run)
	return _c
}

// GetProduct provides a mock function with given fields: ctx, id
func (_m *Repository) GetProduct(ctx context.Context, id int32) (model.Product, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProduct")
	}

	var r0 model.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (model.Product, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) model.Product); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Product)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProduct'
type Repository_GetProduct_Call struct {
	*mock.Call
}

// GetProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *Repository_Expecter) GetProduct(ctx interface{}, id interface{}) *Repository_GetProduct_Call {
	return &Repository_GetProduct_Call{Call: _e.mock.On("GetProduct", ctx, id)}
}

func (_c *Repository_GetProduct_Call) Run(run func(ctx context.Context, id int32)) *Repository_GetProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *Repository_GetProduct_Call) Return(_a0 model.Product, _a1 error) *Repository_GetProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetProduct_Call) RunAndReturn(run func(context.Context, int32) (model.Product, error)) *Repository_GetProduct_Call {
	_c.Call.Return(run)
	return _c
}

// GetWarehouse provides a mock function with given fields: ctx, id
func (_m *Repository) GetWarehouse(ctx context.Context, id int32) (model.Warehouse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetWarehouse")
	}

	var r0 model.Warehouse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (model.Warehouse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) model.Warehouse); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Warehouse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetWarehouse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWarehouse'
type Repository_GetWarehouse_Call struct {
	*mock.Call
}

// GetWarehouse is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *Repository_Expecter) GetWarehouse(ctx interface{}, id interface{}) *Repository_GetWarehouse_Call {
	return &Repository_GetWarehouse_Call{Call: _e.mock.On("GetWarehouse", ctx, id)}
}

func (_c *Repository_GetWarehouse_Call) Run(run func(ctx context.Context, id int32)) *Repository_GetWarehouse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *Repository_GetWarehouse_Call) Return(_a0 model.Warehouse, _a1 error) *Repository_GetWarehouse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetWarehouse_Call) RunAndReturn(run func(context.Context, int32) (model.Warehouse, error)) *Repository_GetWarehouse_Call {
	_c.Call.Return(run)
	return _c
}

// ListProductsByWarehouse provides a mock function with given fields: ctx, warehouseID
func (_m *Repository) ListProductsByWarehouse(ctx context.Context, warehouseID int32) ([]model.Product, error) {
	ret := _m.Called(ctx, warehouseID)

	if len(ret) == 0 {
		panic("no return value specified for ListProductsByWarehouse")
	}

	var r0 []model.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]model.Product, error)); ok {
		return rf(ctx, warehouseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []model.Product); ok {
		r0 = rf(ctx, warehouseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, warehouseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ListProductsByWarehouse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProductsByWarehouse'
type Repository_ListProductsByWarehouse_Call struct {
	*mock.Call
}

// ListProductsByWarehouse is a helper method to define mock.On call
//   - ctx context.Context
//   - warehouseID int32
func (_e *Repository_Expecter) ListProductsByWarehouse(ctx interface{}, warehouseID interface{}) *Repository_ListProductsByWarehouse_Call {
	return &Repository_ListProductsByWarehouse_Call{Call: _e.mock.On("ListProductsByWarehouse", ctx, warehouseID)}
}

func (_c *Repository_ListProductsByWarehouse_Call) Run(run func(ctx context.Context, warehouseID int32)) *Repository_ListProductsByWarehouse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *Repository_ListProductsByWarehouse_Call) Return(_a0 []model.Product, _a1 error) *Repository_ListProductsByWarehouse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ListProductsByWarehouse_Call) RunAndReturn(run func(context.Context, int32) ([]model.Product, error)) *Repository_ListProductsByWarehouse_Call {
	_c.Call.Return(run)
	return _c
}

// ListWarehouses provides a mock function with given fields: ctx
func (_m *Repository) ListWarehouses(ctx context.Context) ([]model.Warehouse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListWarehouses")
	}

	var r0 []model.Warehouse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Warehouse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Warehouse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Warehouse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ListWarehouses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWarehouses'
type Repository_ListWarehouses_Call struct {
	*mock.Call
}

// ListWarehouses is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Repository_Expecter) ListWarehouses(ctx interface{}) *Repository_ListWarehouses_Call {
	return &Repository_ListWarehouses_Call{Call: _e.mock.On("ListWarehouses", ctx)}
}

func (_c *Repository_ListWarehouses_Call) Run(run func(ctx context.Context)) *Repository_ListWarehouses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Repository_ListWarehouses_Call) Return(_a0 []model.Warehouse, _a1 error) *Repository_ListWarehouses_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ListWarehouses_Call) RunAndReturn(run func(context.Context) ([]model.Warehouse, error)) *Repository_ListWarehouses_Call {
	_c.Call.Return(run)
	return _c
}

// SetProductQuantity provides a mock function with given fields: ctx, id, quantity
func (_m *Repository) SetProductQuantity(ctx context.Context, id int32, quantity int32) error {
	ret := _m.Called(ctx, id, quantity)

	if len(ret) == 0 {
		panic("no return value specified for SetProductQuantity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) error); ok {
		r0 = rf(ctx, id, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_SetProductQuantity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetProductQuantity'
type Repository_SetProductQuantity_Call struct {
	*mock.Call
}

// SetProductQuantity is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
//   - quantity int32
func (_e *Repository_Expecter) SetProductQuantity(ctx interface{}, id interface{}, quantity interface{}) *Repository_SetProductQuantity_Call {
	return &Repository_SetProductQuantity_Call{Call: _e.mock.On("SetProductQuantity", ctx, id, quantity)}
}

func (_c *Repository_SetProductQuantity_Call) Run(run func(ctx context.Context, id int32, quantity int32)) *Repository_SetProductQuantity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32))
	})
	return _c
}

func (_c *Repository_SetProductQuantity_Call) Return(_a0 error) *Repository_SetProductQuantity_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_SetProductQuantity_Call) RunAndReturn(run func(context.Context, int32, int32) error) *Repository_SetProductQuantity_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWarehouse provides a mock function with given fields: ctx, id, name, location
func (_m *Repository) UpdateWarehouse(ctx context.Context, id int32, name string, location string) error {
	ret := _m.Called(ctx, id, name, location)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWarehouse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, string, string) error); ok {
		r0 = rf(ctx, id, name, location)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_UpdateWarehouse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWarehouse'
type Repository_UpdateWarehouse_Call struct {
	*mock.Call
}

// UpdateWarehouse is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
//   - name string
//   - location string
func (_e *Repository_Expecter) UpdateWarehouse(ctx interface{}, id interface{}, name interface{}, location interface{}) *Repository_UpdateWarehouse_Call {
	return &Repository_UpdateWarehouse_Call{Call: _e.mock.On("UpdateWarehouse", ctx, id, name, location)}
}

func (_c *Repository_UpdateWarehouse_Call) Run(run func(ctx context.Context, id int32, name string, location string)) *Repository_UpdateWarehouse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *Repository_UpdateWarehouse_Call) Return(_a0 error) *Repository_UpdateWarehouse_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_UpdateWarehouse_Call) RunAndReturn(run func(context.Context, int32, string, string) error) *Repository_UpdateWarehouse_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
