// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/kelar1s/go-freight/internal/inventory/model"
	mock "github.com/stretchr/testify/mock"
)

// NewWarehouseRepo creates a new instance of WarehouseRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWarehouseRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *WarehouseRepo {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &WarehouseRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// WarehouseRepo is an autogenerated mock type for the WarehouseRepo type
type WarehouseRepo struct {
	mock.Mock
}

type WarehouseRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *WarehouseRepo) EXPECT() *WarehouseRepo_Expecter {
	return &WarehouseRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type WarehouseRepo
func (_mock *WarehouseRepo) Create(ctx context.Context, warehouse *model.Warehouse) error {
	ret := _mock.Called(ctx, warehouse)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Warehouse) error); ok {
		r0 = returnFunc(ctx, warehouse)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WarehouseRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type WarehouseRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - warehouse *model.Warehouse
func (_e *WarehouseRepo_Expecter) Create(ctx any, warehouse any) *WarehouseRepo_Create_Call {
	return &WarehouseRepo_Create_Call{Call: _e.mock.On("Create", ctx, warehouse)}
}

func (_c *WarehouseRepo_Create_Call) Run(run func(ctx context.Context, warehouse *model.Warehouse)) *WarehouseRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Warehouse
		if args[1] != nil {
			arg1 = args[1].(*model.Warehouse)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WarehouseRepo_Create_Call) Return(err error) *WarehouseRepo_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WarehouseRepo_Create_Call) RunAndReturn(run func(ctx context.Context, warehouse *model.Warehouse) error) *WarehouseRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type WarehouseRepo
func (_mock *WarehouseRepo) Delete(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WarehouseRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type WarehouseRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *WarehouseRepo_Expecter) Delete(ctx any, id any) *WarehouseRepo_Delete_Call {
	return &WarehouseRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *WarehouseRepo_Delete_Call) Run(run func(ctx context.Context, id int64)) *WarehouseRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WarehouseRepo_Delete_Call) Return(err error) *WarehouseRepo_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WarehouseRepo_Delete_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *WarehouseRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type WarehouseRepo
func (_mock *WarehouseRepo) Get(ctx context.Context, id int64) (*model.Warehouse, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Warehouse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*model.Warehouse, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *model.Warehouse); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Warehouse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WarehouseRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type WarehouseRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *WarehouseRepo_Expecter) Get(ctx any, id any) *WarehouseRepo_Get_Call {
	return &WarehouseRepo_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *WarehouseRepo_Get_Call) Run(run func(ctx context.Context, id int64)) *WarehouseRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WarehouseRepo_Get_Call) Return(warehouse *model.Warehouse, err error) *WarehouseRepo_Get_Call {
	_c.Call.Return(warehouse, err)
	return _c
}

func (_c *WarehouseRepo_Get_Call) RunAndReturn(run func(ctx context.Context, id int64) (*model.Warehouse, error)) *WarehouseRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type WarehouseRepo
func (_mock *WarehouseRepo) List(ctx context.Context) ([]model.Warehouse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Warehouse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Warehouse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Warehouse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Warehouse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WarehouseRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type WarehouseRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *WarehouseRepo_Expecter) List(ctx any) *WarehouseRepo_List_Call {
	return &WarehouseRepo_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *WarehouseRepo_List_Call) Run(run func(ctx context.Context)) *WarehouseRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WarehouseRepo_List_Call) Return(warehouses []model.Warehouse, err error) *WarehouseRepo_List_Call {
	_c.Call.Return(warehouses, err)
	return _c
}

func (_c *WarehouseRepo_List_Call) RunAndReturn(run func(ctx context.Context) ([]model.Warehouse, error)) *WarehouseRepo_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type WarehouseRepo
func (_mock *WarehouseRepo) Update(ctx context.Context, warehouse *model.Warehouse) error {
	ret := _mock.Called(ctx, warehouse)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Warehouse) error); ok {
		r0 = returnFunc(ctx, warehouse)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WarehouseRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type WarehouseRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - warehouse *model.Warehouse
func (_e *WarehouseRepo_Expecter) Update(ctx any, warehouse any) *WarehouseRepo_Update_Call {
	return &WarehouseRepo_Update_Call{Call: _e.mock.On("Update", ctx, warehouse)}
}

func (_c *WarehouseRepo_Update_Call) Run(run func(ctx context.Context, warehouse *model.Warehouse)) *WarehouseRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Warehouse
		if args[1] != nil {
			arg1 = args[1].(*model.Warehouse)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WarehouseRepo_Update_Call) Return(err error) *WarehouseRepo_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WarehouseRepo_Update_Call) RunAndReturn(run func(ctx context.Context, warehouse *model.Warehouse) error) *WarehouseRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}
