// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/kelar1s/go-freight/internal/inventory/model"
	mock "github.com/stretchr/testify/mock"
)

// WarehouseRepo is an autogenerated mock type for the WarehouseRepo type
type WarehouseRepo struct {
	mock.Mock
}

type WarehouseRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *WarehouseRepo) EXPECT() *WarehouseRepo_Expecter {
	return &WarehouseRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, warehouse
func (_m *WarehouseRepo) Create(ctx context.Context, warehouse *model.Warehouse) error {
	ret := _m.Called(ctx, warehouse)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Warehouse) error); ok {
		r0 = rf(ctx, warehouse)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WarehouseRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type WarehouseRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - warehouse *model.Warehouse
func (_e *WarehouseRepo_Expecter) Create(ctx interface{}, warehouse interface{}) *WarehouseRepo_Create_Call {
	return &WarehouseRepo_Create_Call{Call: _e.mock.On("Create", ctx, warehouse)}
}

func (_c *WarehouseRepo_Create_Call) Run(run func(ctx context.Context, warehouse *model.Warehouse)) *WarehouseRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Warehouse))
	})
	return _c
}

func (_c *WarehouseRepo_Create_Call) Return(_a0 error) *WarehouseRepo_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WarehouseRepo_Create_Call) RunAndReturn(run func(context.Context, *model.Warehouse) error) *WarehouseRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *WarehouseRepo) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WarehouseRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type WarehouseRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *WarehouseRepo_Expecter) Delete(ctx interface{}, id interface{}) *WarehouseRepo_Delete_Call {
	return &WarehouseRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *WarehouseRepo_Delete_Call) Run(run func(ctx context.Context, id int64)) *WarehouseRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *WarehouseRepo_Delete_Call) Return(_a0 error) *WarehouseRepo_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WarehouseRepo_Delete_Call) RunAndReturn(run func(context.Context, int64) error) *WarehouseRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *WarehouseRepo) Get(ctx context.Context, id int64) (*model.Warehouse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Warehouse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.Warehouse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.Warehouse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Warehouse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WarehouseRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type WarehouseRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *WarehouseRepo_Expecter) Get(ctx interface{}, id interface{}) *WarehouseRepo_Get_Call {
	return &WarehouseRepo_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *WarehouseRepo_Get_Call) Run(run func(ctx context.Context, id int64)) *WarehouseRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *WarehouseRepo_Get_Call) Return(_a0 *model.Warehouse, _a1 error) *WarehouseRepo_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WarehouseRepo_Get_Call) RunAndReturn(run func(context.Context, int64) (*model.Warehouse, error)) *WarehouseRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *WarehouseRepo) List(ctx context.Context) ([]model.Warehouse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Warehouse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Warehouse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Warehouse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Warehouse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WarehouseRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type WarehouseRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *WarehouseRepo_Expecter) List(ctx interface{}) *WarehouseRepo_List_Call {
	return &WarehouseRepo_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *WarehouseRepo_List_Call) Run(run func(ctx context.Context)) *WarehouseRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *WarehouseRepo_List_Call) Return(_a0 []model.Warehouse, _a1 error) *WarehouseRepo_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WarehouseRepo_List_Call) RunAndReturn(run func(context.Context) ([]model.Warehouse, error)) *WarehouseRepo_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, warehouse
func (_m *WarehouseRepo) Update(ctx context.Context, warehouse *model.Warehouse) error {
	ret := _m.Called(ctx, warehouse)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Warehouse) error); ok {
		r0 = rf(ctx, warehouse)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WarehouseRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type WarehouseRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - warehouse *model.Warehouse
func (_e *WarehouseRepo_Expecter) Update(ctx interface{}, warehouse interface{}) *WarehouseRepo_Update_Call {
	return &WarehouseRepo_Update_Call{Call: _e.mock.On("Update", ctx, warehouse)}
}

func (_c *WarehouseRepo_Update_Call) Run(run func(ctx context.Context, warehouse *model.Warehouse)) *WarehouseRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Warehouse))
	})
	return _c
}

func (_c *WarehouseRepo_Update_Call) Return(_a0 error) *WarehouseRepo_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WarehouseRepo_Update_Call) RunAndReturn(run func(context.Context, *model.Warehouse) error) *WarehouseRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewWarehouseRepo creates a new instance of WarehouseRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWarehouseRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *WarehouseRepo {
	mock := &WarehouseRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
