// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/kelar1s/go-freight/internal/inventory/model"
	mock "github.com/stretchr/testify/mock"
)

// NewProductService creates a new instance of ProductService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &ProductService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// ProductService is an autogenerated mock type for the ProductService type
type ProductService struct {
	mock.Mock
}

type ProductService_Expecter struct {
	mock *mock.Mock
}

func (_m *ProductService) EXPECT() *ProductService_Expecter {
	return &ProductService_Expecter{mock: &_m.Mock}
}

// AdjustQuantity provides a mock function for the type ProductService
func (_mock *ProductService) AdjustQuantity(ctx context.Context, id int64, quantity int64) error {
	ret := _mock.Called(ctx, id, quantity)

	if len(ret) == 0 {
		panic("no return value specified for AdjustQuantity")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, id, quantity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProductService_AdjustQuantity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdjustQuantity'
type ProductService_AdjustQuantity_Call struct {
	*mock.Call
}

// AdjustQuantity is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - quantity int64
func (_e *ProductService_Expecter) AdjustQuantity(ctx any, id any, quantity any) *ProductService_AdjustQuantity_Call {
	return &ProductService_AdjustQuantity_Call{Call: _e.mock.On("AdjustQuantity", ctx, id, quantity)}
}

func (_c *ProductService_AdjustQuantity_Call) Run(run func(ctx context.Context, id int64, quantity int64)) *ProductService_AdjustQuantity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProductService_AdjustQuantity_Call) Return(err error) *ProductService_AdjustQuantity_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProductService_AdjustQuantity_Call) RunAndReturn(run func(ctx context.Context, id int64, quantity int64) error) *ProductService_AdjustQuantity_Call {
	_c.Call.Return(run)
	return _c
}

// CancelReservation provides a mock function for the type ProductService
func (_mock *ProductService) CancelReservation(ctx context.Context, id int64, quantity int64) error {
	ret := _mock.Called(ctx, id, quantity)

	if len(ret) == 0 {
		panic("no return value specified for CancelReservation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, id, quantity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProductService_CancelReservation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelReservation'
type ProductService_CancelReservation_Call struct {
	*mock.Call
}

// CancelReservation is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - quantity int64
func (_e *ProductService_Expecter) CancelReservation(ctx any, id any, quantity any) *ProductService_CancelReservation_Call {
	return &ProductService_CancelReservation_Call{Call: _e.mock.On("CancelReservation", ctx, id, quantity)}
}

func (_c *ProductService_CancelReservation_Call) Run(run func(ctx context.Context, id int64, quantity int64)) *ProductService_CancelReservation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProductService_CancelReservation_Call) Return(err error) *ProductService_CancelReservation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProductService_CancelReservation_Call) RunAndReturn(run func(ctx context.Context, id int64, quantity int64) error) *ProductService_CancelReservation_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type ProductService
func (_mock *ProductService) Create(ctx context.Context, warehouseID int64, name string, quantity int64) (*model.Product, error) {
	ret := _mock.Called(ctx, warehouseID, name, quantity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, int64) (*model.Product, error)); ok {
		return returnFunc(ctx, warehouseID, name, quantity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, int64) *model.Product); ok {
		r0 = returnFunc(ctx, warehouseID, name, quantity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string, int64) error); ok {
		r1 = returnFunc(ctx, warehouseID, name, quantity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProductService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ProductService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - warehouseID int64
//   - name string
//   - quantity int64
func (_e *ProductService_Expecter) Create(ctx any, warehouseID any, name any, quantity any) *ProductService_Create_Call {
	return &ProductService_Create_Call{Call: _e.mock.On("Create", ctx, warehouseID, name, quantity)}
}

func (_c *ProductService_Create_Call) Run(run func(ctx context.Context, warehouseID int64, name string, quantity int64)) *ProductService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ProductService_Create_Call) Return(product *model.Product, err error) *ProductService_Create_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *ProductService_Create_Call) RunAndReturn(run func(ctx context.Context, warehouseID int64, name string, quantity int64) (*model.Product, error)) *ProductService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type ProductService
func (_mock *ProductService) Delete(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProductService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ProductService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *ProductService_Expecter) Delete(ctx any, id any) *ProductService_Delete_Call {
	return &ProductService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *ProductService_Delete_Call) Run(run func(ctx context.Context, id int64)) *ProductService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductService_Delete_Call) Return(err error) *ProductService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProductService_Delete_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *ProductService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type ProductService
func (_mock *ProductService) Get(ctx context.Context, id int64) (*model.Product, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*model.Product, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *model.Product); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProductService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ProductService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *ProductService_Expecter) Get(ctx any, id any) *ProductService_Get_Call {
	return &ProductService_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *ProductService_Get_Call) Run(run func(ctx context.Context, id int64)) *ProductService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductService_Get_Call) Return(product *model.Product, err error) *ProductService_Get_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *ProductService_Get_Call) RunAndReturn(run func(ctx context.Context, id int64) (*model.Product, error)) *ProductService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListByWarehouse provides a mock function for the type ProductService
func (_mock *ProductService) ListByWarehouse(ctx context.Context, warehouseID int64) ([]model.Product, error) {
	ret := _mock.Called(ctx, warehouseID)

	if len(ret) == 0 {
		panic("no return value specified for ListByWarehouse")
	}

	var r0 []model.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]model.Product, error)); ok {
		return returnFunc(ctx, warehouseID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []model.Product); ok {
		r0 = returnFunc(ctx, warehouseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, warehouseID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProductService_ListByWarehouse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByWarehouse'
type ProductService_ListByWarehouse_Call struct {
	*mock.Call
}

// ListByWarehouse is a helper method to define mock.On call
//   - ctx context.Context
//   - warehouseID int64
func (_e *ProductService_Expecter) ListByWarehouse(ctx any, warehouseID any) *ProductService_ListByWarehouse_Call {
	return &ProductService_ListByWarehouse_Call{Call: _e.mock.On("ListByWarehouse", ctx, warehouseID)}
}

func (_c *ProductService_ListByWarehouse_Call) Run(run func(ctx context.Context, warehouseID int64)) *ProductService_ListByWarehouse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductService_ListByWarehouse_Call) Return(products []model.Product, err error) *ProductService_ListByWarehouse_Call {
	_c.Call.Return(products, err)
	return _c
}

func (_c *ProductService_ListByWarehouse_Call) RunAndReturn(run func(ctx context.Context, warehouseID int64) ([]model.Product, error)) *ProductService_ListByWarehouse_Call {
	_c.Call.Return(run)
	return _c
}

// Release provides a mock function for the type ProductService
func (_mock *ProductService) Release(ctx context.Context, id int64, quantity int64) error {
	ret := _mock.Called(ctx, id, quantity)

	if len(ret) == 0 {
		panic("no return value specified for Release")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, id, quantity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProductService_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type ProductService_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - quantity int64
func (_e *ProductService_Expecter) Release(ctx any, id any, quantity any) *ProductService_Release_Call {
	return &ProductService_Release_Call{Call: _e.mock.On("Release", ctx, id, quantity)}
}

func (_c *ProductService_Release_Call) Run(run func(ctx context.Context, id int64, quantity int64)) *ProductService_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProductService_Release_Call) Return(err error) *ProductService_Release_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProductService_Release_Call) RunAndReturn(run func(ctx context.Context, id int64, quantity int64) error) *ProductService_Release_Call {
	_c.Call.Return(run)
	return _c
}

// Reserve provides a mock function for the type ProductService
func (_mock *ProductService) Reserve(ctx context.Context, id int64, quantity int64) error {
	ret := _mock.Called(ctx, id, quantity)

	if len(ret) == 0 {
		panic("no return value specified for Reserve")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, id, quantity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProductService_Reserve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reserve'
type ProductService_Reserve_Call struct {
	*mock.Call
}

// Reserve is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - quantity int64
func (_e *ProductService_Expecter) Reserve(ctx any, id any, quantity any) *ProductService_Reserve_Call {
	return &ProductService_Reserve_Call{Call: _e.mock.On("Reserve", ctx, id, quantity)}
}

func (_c *ProductService_Reserve_Call) Run(run func(ctx context.Context, id int64, quantity int64)) *ProductService_Reserve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProductService_Reserve_Call) Return(err error) *ProductService_Reserve_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProductService_Reserve_Call) RunAndReturn(run func(ctx context.Context, id int64, quantity int64) error) *ProductService_Reserve_Call {
	_c.Call.Return(run)
	return _c
}
