// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/kelar1s/go-freight/internal/inventory/model"
	mock "github.com/stretchr/testify/mock"
)

// WarehouseService is an autogenerated mock type for the WarehouseService type
type WarehouseService struct {
	mock.Mock
}

type WarehouseService_Expecter struct {
	mock *mock.Mock
}

func (_m *WarehouseService) EXPECT() *WarehouseService_Expecter {
	return &WarehouseService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, name, location
func (_m *WarehouseService) Create(ctx context.Context, name string, location string) (*model.Warehouse, error) {
	ret := _m.Called(ctx, name, location)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Warehouse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.Warehouse, error)); ok {
		return rf(ctx, name, location)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.Warehouse); ok {
		r0 = rf(ctx, name, location)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Warehouse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, name, location)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WarehouseService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type WarehouseService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - location string
func (_e *WarehouseService_Expecter) Create(ctx interface{}, name interface{}, location interface{}) *WarehouseService_Create_Call {
	return &WarehouseService_Create_Call{Call: _e.mock.On("Create", ctx, name, location)}
}

func (_c *WarehouseService_Create_Call) Run(run func(ctx context.Context, name string, location string)) *WarehouseService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *WarehouseService_Create_Call) Return(_a0 *model.Warehouse, _a1 error) *WarehouseService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WarehouseService_Create_Call) RunAndReturn(run func(context.Context, string, string) (*model.Warehouse, error)) *WarehouseService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *WarehouseService) Delete(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WarehouseService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type WarehouseService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *WarehouseService_Expecter) Delete(ctx interface{}, id interface{}) *WarehouseService_Delete_Call {
	return &WarehouseService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *WarehouseService_Delete_Call) Run(run func(ctx context.Context, id int32)) *WarehouseService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *WarehouseService_Delete_Call) Return(_a0 error) *WarehouseService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WarehouseService_Delete_Call) RunAndReturn(run func(context.Context, int32) error) *WarehouseService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *WarehouseService) Get(ctx context.Context, id int32) (*model.Warehouse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Warehouse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (*model.Warehouse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) *model.Warehouse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Warehouse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WarehouseService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type WarehouseService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *WarehouseService_Expecter) Get(ctx interface{}, id interface{}) *WarehouseService_Get_Call {
	return &WarehouseService_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *WarehouseService_Get_Call) Run(run func(ctx context.Context, id int32)) *WarehouseService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *WarehouseService_Get_Call) Return(_a0 *model.Warehouse, _a1 error) *WarehouseService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WarehouseService_Get_Call) RunAndReturn(run func(context.Context, int32) (*model.Warehouse, error)) *WarehouseService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *WarehouseService) List(ctx context.Context) ([]model.Warehouse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Warehouse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Warehouse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Warehouse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Warehouse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WarehouseService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type WarehouseService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *WarehouseService_Expecter) List(ctx interface{}) *WarehouseService_List_Call {
	return &WarehouseService_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *WarehouseService_List_Call) Run(run func(ctx context.Context)) *WarehouseService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *WarehouseService_List_Call) Return(_a0 []model.Warehouse, _a1 error) *WarehouseService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WarehouseService_List_Call) RunAndReturn(run func(context.Context) ([]model.Warehouse, error)) *WarehouseService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, name, location
func (_m *WarehouseService) Update(ctx context.Context, id int32, name string, location string) error {
	ret := _m.Called(ctx, id, name, location)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, string, string) error); ok {
		r0 = rf(ctx, id, name, location)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WarehouseService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type WarehouseService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
//   - name string
//   - location string
func (_e *WarehouseService_Expecter) Update(ctx interface{}, id interface{}, name interface{}, location interface{}) *WarehouseService_Update_Call {
	return &WarehouseService_Update_Call{Call: _e.mock.On("Update", ctx, id, name, location)}
}

func (_c *WarehouseService_Update_Call) Run(run func(ctx context.Context, id int32, name string, location string)) *WarehouseService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *WarehouseService_Update_Call) Return(_a0 error) *WarehouseService_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WarehouseService_Update_Call) RunAndReturn(run func(context.Context, int32, string, string) error) *WarehouseService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewWarehouseService creates a new instance of WarehouseService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWarehouseService(t interface {
	mock.TestingT
	Cleanup(func())
}) *WarehouseService {
	mock := &WarehouseService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
