// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/kelar1s/go-freight/internal/inventory/model"
	mock "github.com/stretchr/testify/mock"
)

// NewWarehouseService creates a new instance of WarehouseService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWarehouseService(t interface {
	mock.TestingT
	Cleanup(func())
}) *WarehouseService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &WarehouseService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// WarehouseService is an autogenerated mock type for the WarehouseService type
type WarehouseService struct {
	mock.Mock
}

type WarehouseService_Expecter struct {
	mock *mock.Mock
}

func (_m *WarehouseService) EXPECT() *WarehouseService_Expecter {
	return &WarehouseService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type WarehouseService
func (_mock *WarehouseService) Create(ctx context.Context, name string, location string) (*model.Warehouse, error) {
	ret := _mock.Called(ctx, name, location)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Warehouse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.Warehouse, error)); ok {
		return returnFunc(ctx, name, location)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.Warehouse); ok {
		r0 = returnFunc(ctx, name, location)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Warehouse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, name, location)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WarehouseService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type WarehouseService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - location string
func (_e *WarehouseService_Expecter) Create(ctx any, name any, location any) *WarehouseService_Create_Call {
	return &WarehouseService_Create_Call{Call: _e.mock.On("Create", ctx, name, location)}
}

func (_c *WarehouseService_Create_Call) Run(run func(ctx context.Context, name string, location string)) *WarehouseService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WarehouseService_Create_Call) Return(warehouse *model.Warehouse, err error) *WarehouseService_Create_Call {
	_c.Call.Return(warehouse, err)
	return _c
}

func (_c *WarehouseService_Create_Call) RunAndReturn(run func(ctx context.Context, name string, location string) (*model.Warehouse, error)) *WarehouseService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type WarehouseService
func (_mock *WarehouseService) Delete(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WarehouseService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type WarehouseService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *WarehouseService_Expecter) Delete(ctx any, id any) *WarehouseService_Delete_Call {
	return &WarehouseService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *WarehouseService_Delete_Call) Run(run func(ctx context.Context, id int64)) *WarehouseService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WarehouseService_Delete_Call) Return(err error) *WarehouseService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WarehouseService_Delete_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *WarehouseService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type WarehouseService
func (_mock *WarehouseService) Get(ctx context.Context, id int64) (*model.Warehouse, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Warehouse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*model.Warehouse, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *model.Warehouse); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Warehouse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WarehouseService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type WarehouseService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *WarehouseService_Expecter) Get(ctx any, id any) *WarehouseService_Get_Call {
	return &WarehouseService_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *WarehouseService_Get_Call) Run(run func(ctx context.Context, id int64)) *WarehouseService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WarehouseService_Get_Call) Return(warehouse *model.Warehouse, err error) *WarehouseService_Get_Call {
	_c.Call.Return(warehouse, err)
	return _c
}

func (_c *WarehouseService_Get_Call) RunAndReturn(run func(ctx context.Context, id int64) (*model.Warehouse, error)) *WarehouseService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type WarehouseService
func (_mock *WarehouseService) List(ctx context.Context) ([]model.Warehouse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Warehouse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Warehouse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Warehouse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Warehouse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WarehouseService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type WarehouseService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *WarehouseService_Expecter) List(ctx any) *WarehouseService_List_Call {
	return &WarehouseService_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *WarehouseService_List_Call) Run(run func(ctx context.Context)) *WarehouseService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WarehouseService_List_Call) Return(warehouses []model.Warehouse, err error) *WarehouseService_List_Call {
	_c.Call.Return(warehouses, err)
	return _c
}

func (_c *WarehouseService_List_Call) RunAndReturn(run func(ctx context.Context) ([]model.Warehouse, error)) *WarehouseService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type WarehouseService
func (_mock *WarehouseService) Update(ctx context.Context, id int64, name string, location string) error {
	ret := _mock.Called(ctx, id, name, location)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string) error); ok {
		r0 = returnFunc(ctx, id, name, location)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WarehouseService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type WarehouseService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - name string
//   - location string
func (_e *WarehouseService_Expecter) Update(ctx any, id any, name any, location any) *WarehouseService_Update_Call {
	return &WarehouseService_Update_Call{Call: _e.mock.On("Update", ctx, id, name, location)}
}

func (_c *WarehouseService_Update_Call) Run(run func(ctx context.Context, id int64, name string, location string)) *WarehouseService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *WarehouseService_Update_Call) Return(err error) *WarehouseService_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WarehouseService_Update_Call) RunAndReturn(run func(ctx context.Context, id int64, name string, location string) error) *WarehouseService_Update_Call {
	_c.Call.Return(run)
	return _c
}
