basePath: /api/v1
definitions:
  github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.AdjustProductQuantityRequest:
    properties:
      quantity:
        type: integer
    type: object
  github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.CancelReservationRequest:
    properties:
      quantity:
        type: integer
    type: object
  github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.CreateProductRequest:
    properties:
      name:
        type: string
      quantity:
        type: integer
      warehouse_id:
        type: integer
    type: object
  github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.CreateWarehouseRequest:
    properties:
      location:
        type: string
      name:
        type: string
    type: object
  github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ProductResponse:
    properties:
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      quantity:
        type: integer
      reserved:
        type: integer
      warehouse_id:
        type: integer
    type: object
  github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ReleaseProductRequest:
    properties:
      quantity:
        type: integer
    type: object
  github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ReserveProductRequest:
    properties:
      quantity:
        type: integer
    type: object
  github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.UpdateWarehouseRequest:
    properties:
      location:
        type: string
      name:
        type: string
    type: object
  github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.WarehouseResponse:
    properties:
      created_at:
        type: string
      id:
        type: integer
      location:
        type: string
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Сервис управления складами и товарами.
  title: Go-Freight Inventory API
  version: "1.0"
paths:
  /products:
    post:
      consumes:
      - application/json
      description: Создает товар с указанием ID склада, названия и начального количества
      parameters:
      - description: Данные товара
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.CreateProductRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ProductResponse'
        "400":
          description: Невалидные данные (например, пустое имя)
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
      summary: Создать новый товар
      tags:
      - products
  /products/{id}:
    delete:
      description: Удаляет запись о товаре по его ID
      parameters:
      - description: ID товара
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
      summary: Удалить товар
      tags:
      - products
    get:
      description: Возвращает информацию о товаре и его остатках по ID
      parameters:
      - description: ID товара
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ProductResponse'
        "400":
          description: Неверный формат ID
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
        "404":
          description: Товар не найден
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
      summary: Получить товар по ID
      tags:
      - products
  /products/{id}/adjust:
    patch:
      consumes:
      - application/json
      description: Увеличивает или уменьшает остаток товара на складе на переданную
        дельту
      parameters:
      - description: ID товара
        in: path
        name: id
        required: true
        type: integer
      - description: Дельта изменения остатка (+/-)
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.AdjustProductQuantityRequest'
      responses:
        "204":
          description: No Content
        "400":
          description: Некорректный ID или тело запроса
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
        "404":
          description: Товар не найден
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
        "409":
          description: 'Конфликт: недостаточно товара на складе'
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
      summary: Скорректировать остаток товара
      tags:
      - products
  /products/{id}/cancel-reservation:
    patch:
      consumes:
      - application/json
      description: Снимает резерв с товара
      parameters:
      - description: ID товара
        in: path
        name: id
        required: true
        type: integer
      - description: Количество для отмены брони
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.CancelReservationRequest'
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
        "409":
          description: Попытка отменить больше резерва, чем существует
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
      summary: Отменить резерв товара
      tags:
      - products
  /products/{id}/release:
    patch:
      consumes:
      - application/json
      description: Списывает товар со склада после успешной отгрузки
      parameters:
      - description: ID товара
        in: path
        name: id
        required: true
        type: integer
      - description: Количество для списания
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ReleaseProductRequest'
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
        "409":
          description: Попытка списать больше, чем зарезервировано
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
      summary: Списать зарезервированный товар
      tags:
      - products
  /products/{id}/reserve:
    patch:
      consumes:
      - application/json
      description: Резервирует указанное количество товара
      parameters:
      - description: ID товара
        in: path
        name: id
        required: true
        type: integer
      - description: Количество для резерва
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ReserveProductRequest'
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
        "409":
          description: Недостаточно свободного товара для резервирования
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
      summary: Зарезервировать товар
      tags:
      - products
  /warehouses:
    get:
      description: Возвращает список всех зарегистрированных складов в системе
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.WarehouseResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
      summary: Получить список всех складов
      tags:
      - warehouses
    post:
      consumes:
      - application/json
      description: Регистрирует новый склад с указанием названия и адреса
      parameters:
      - description: Данные склада
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.CreateWarehouseRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.WarehouseResponse'
        "400":
          description: Отсутствует название или локация
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
      summary: Создать новый склад
      tags:
      - warehouses
  /warehouses/{id}:
    delete:
      description: Удаляет склад по его ID
      parameters:
      - description: ID склада
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
      summary: Удалить склад
      tags:
      - warehouses
    get:
      description: Возвращает детальную информацию о складе по его идентификатору
      parameters:
      - description: ID склада
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.WarehouseResponse'
        "400":
          description: Неверный формат ID
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
        "404":
          description: Склад не найден
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
      summary: Получить склад по ID
      tags:
      - warehouses
    put:
      consumes:
      - application/json
      description: Полностью обновляет название и локацию склада по его ID
      parameters:
      - description: ID склада
        in: path
        name: id
        required: true
        type: integer
      - description: Новые данные склада
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.UpdateWarehouseRequest'
      responses:
        "204":
          description: No Content
        "400":
          description: Неверный формат ID или неполные данные
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
        "404":
          description: Склад не найден
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
      summary: Обновить данные склада
      tags:
      - warehouses
  /warehouses/{id}/products:
    get:
      description: Возвращает все товары, привязанные к конкретному складу
      parameters:
      - description: ID склада
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ProductResponse'
            type: array
        "400":
          description: Неверный формат ID склада
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_kelar1s_go-freight_internal_inventory_transport_rest_dto.ErrorResponse'
      summary: Получить список товаров на складе
      tags:
      - products
swagger: "2.0"
